### ISSUE TITLE
3rd option shows some bugs sir.

### ISSUE THREAD

**Issue by cpavanrun** [UiL-OTS-labs-backoffice/Facility-Reservation-and-Information-System-FRIS-#7]
Page https://fris.hum.uu.nl/index.php?page=facres-all 
Dropdown menu for **Slots** shows literal on the third option `<br/>`

**Comment by AJdeMooij** [comment]
Not a bug per se. Each of the items actually contains those tags, because in a previous area, the markup was done there, which shouldn't happen.

All characters get escaped to HTML entities to make sure nothing breaks at the wrong moments. So that page just displays what it receives.

The third option is never used, by the way, so we could remove it
